---
- name: create resources to build a VM
  hosts: localhost
  # tasks:
  # - name: Create a resource group
  # azure_rm_resourcegroup:
  #   subscription_id: "{{subscription_id}}"
  #   state: present
  #   name: "{{Resources_group_name}}"
  #   location: "{{location}}"
  #   tags:
  #     owner: "Anoop Maurya"
  #     phone: XXXXXXXXXXXXX
      email: xyz@domain.com

- name: Create a virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{Resources_group_name}}"
    name: "{{name}}"
    address_prefixes_cidr:
      - 192.168.0.0/16
    dns_servers:
      - 8.8.8.8
    tags:
      testing: testing
      delete: on-exit

- name: Create a securiy group
  azure_rm_securitygroup:
    name: "{{name}}"
    resource_group: "{{Resources_group_name}}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 105
        direction: Inbound
      - name: ICMP
        protocol: Icmp
        priority: 106

- name: Create a subnet
  azure_rm_subnet:
    resource_group: "{{Resources_group_name}}"
    virtual_network_name: "{{name}}"
    name: mySubnet
    address_prefix_cidr: "192.168.1.0/24"
    security_group:
      name: "{{name}}"
      resource_group: "{{Resources_group_name}}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{Resources_group_name}}"
    name: "{{vm_name}}"
    admin_username: "{{ username }}"
    admin_password: "{{ password }}"
    image:
      # offer: "{{os_image}}"
      # publisher: "{{publisher}}"
      # sku: "{{sku}}"
      # version: "{{version}}"
      vm_size: Standard_E2s_v3 - 2 vcpus, 16 GiB memory 
      architecture: x64
      offer: ubuntu-24_04-lts
      publisher: Canonical
      sku: ubuntu-pro
      urn: Canonical:ubuntu-24_04-lts:ubuntu-pro:latest
      urnAlias: Ubuntu2404Pro
      version: latest

