---
- hosts: all
  become: true
  tasks:
    - name: "User Add on ubuntu Server"
      ansible.builtin.user:
        name: test
        create_home: yes
        shell: /bin/bash
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
