---
- name: "User Add on ubuntu Server"
  ansible.builtin.user:
    name: "{{ user }}" # user name defile in default folder,
    create_home: yes
    shell: /bin/bash
    state: present
    groups: anoop
    append: yes
    password_expire_min: 10
    password_expire_max: 90
    password_expire_warn: 7
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
