---
- name: configuriung hostname
  ansible.builtin.hostname:
    name: Web-server

- name: Print current working directory
  ansible.builtin.command: pwd
  register: result

- name: Show result
  ansible.builtin.debug:
    var: result.stdout

- name: Print current working directory
  ansible.builtin.command: ls -ll /home/anoop
  register: result2

- name: Show result2
  ansible.builtin.debug:
    var: result2.stdout

- name: Copy Docker file with owner and permissions
  copy:
    src: /mnt/d/Git-Repo/Ansible/Configuration/server-configuration/files/docker-setup.sh
    dest: /root/docker-setup.sh
    owner: root
    group: root
    mode: '0766'


- name: Docker install throgh shell script
  ansible.builtin.shell: ~/docker-setup.sh >> /var/log/docker-setup.log

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: anoop
    group: anoop
    mode: '0666'

- name: Time and Date
  ansible.builtin.shell: sudo systemctl restart ntp && \
                         sudo timedatectl set-timezone Asia/Kolkata 
